### ISSUE TITLE
Joke or not, dangerous

### ISSUE THREAD

**Issue by dazoe** [amidaware/tacticalrmm-web#5]
https://github.com/amidaware/tacticalrmm-web/blob/3a45c2a30910b5da50b814f3ca6285576aaa5aa4/src/composables/agents.js#L31

This may be a joke but I know some where some one will try to run the placeholder command. Maybe change it to something a bit safer?

**Comment by dinger1986** [comment]
As in type the command out to see what it will do?

**Comment by dazoe** [comment]
That's what I was thinking. They click on run command and see the placeholder text and type it out just to see what it will do.

**Comment by dinger1986** [comment]
Do you want to PR a change? 

I'd be really worried about someone having an RMM tool and god privileges on a machine and not know immediately that the place holder text is a joke!

It probably does need changed at some point however

**Comment by dazoe** [comment]
I worked at a few MSPs and yes, there are people out there with access to RMM tools that wouldn't know what that command does. Mostly due to the fact that they are more GUI oriented type and don't do much with command line.
As for a different command for an example, not sure what would be a good example to use. Need to be something that can easily be converted to each of the other example but also something to showcase the ability to use flag options and arguments. Suggestions? I was thinking of something simple like ping with a few options? Will need to have options for the linux example due to the default of pinging for ever.

**Comment by dinger1986** [comment]
Guess ping would be fine, not saying it will be accepted as it's not my decision

**Comment by wh1te909** [comment]
TRMM has a permissions system where you can prevent users from sending commands and/or running scripts. Someone who doesn't understand what the placeholder command does should either have restricted permissions, or better yet not have RMM access at all since they will inevitably run some other dangerous command and bork the system. 

Anyway this was just an easter egg that I added like 4 years ago from the very beginning and never bothered to change it cuz so many people have found it funny. What I can do is make the placeholder text customizable so you can make it say whatever you want. I will implement this in the next release and update the docs with instructions on how to change the placeholder text to whatever you want.

**Comment by dazoe** [comment]
Sounds like a good option

**Comment by wh1te909** [comment]
added, will be in next release
